apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose/docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
      - name: postgresql
        image: localhost:5000/bitnami/postgresql:11-debian-10
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: dockercompose-postgresql-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: dockercompose-postgresql-data
        persistentVolumeClaim:
          claimName: dockercompose-postgresql-data
status: {}
